io-services:
  reader:
    class: org.jlab.io.clara.HipoToHipoReader
    name: HipoToHipoReader
  writer:
    class: org.jlab.io.clara.HipoToHipoWriter
    name: HipoToHipoWriter
services:
  - class: org.jlab.clas.swimtools.MagFieldsEngine
    name: MAGFIELDS
#ALERT subsystems
#  - class: org.jlab.service.atof.ATOFEngine
#    name: ATOF
  - class: org.jlab.service.ahdc.AHDCEngine
    name: AHDC

configuration:
  global:
    variation: rge_spring2024
#    timestamp: 06/24/2025-09:00:00
  io-services:
    writer:
      schema_dir: "/w/hallb-scshelf2102/clas12/users/touchte/coatjava/coatjava/etc/bankdefs/hipo4/singles/mon/"
  services:
    MAGFIELDS:
      magfieldSolenoidMap: Symm_solenoid_r601_phi1_z1201_13June2018.dat
      magfieldTorusMap: Full_torus_r251_phi181_z251_25Jan2021.dat
    AHDC:
      Mode: "AI_Track_Finding"  
mime-types:
  - binary/data-hipo
